pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/your-username/gate-registration-app.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t your-dockerhub-username/gate-registration-app:latest .'
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-pass', variable: 'DOCKER_HUB_PASS')]) {
                    sh "echo $DOCKER_HUB_PASS | docker login -u your-dockerhub-username --password-stdin"
                    sh 'docker push your-dockerhub-username/gate-registration-app:latest'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 8080:8080 your-dockerhub-username/gate-registration-app:latest'
            }
        }
    }
}